name: Deploy to Server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            set -e

            APP_DIR="/var/www/sshappy"
            REPO_URL="https://github.com/dutchiono/sshappy.git"

            echo "Starting deployment..."

            if [ -d "$APP_DIR/.git" ]; then
              echo "Pulling latest changes..."
              cd $APP_DIR
              git pull origin main
            else
              echo "Initial clone..."
              git clone $REPO_URL $APP_DIR
              cd $APP_DIR
            fi

            echo "Installing dependencies..."
            npm install

            echo "Restarting service..."
            sudo systemctl restart sshappy.service

            echo "Deployment complete at $(date)"