name: Build and Deploy SSHappy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: EAS Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test -- --passWithNoTests

      - name: EAS Build (Preview APK)
        run: eas build --platform android --profile preview --non-interactive --no-wait

  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy website to server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            # Create app directory if it doesn't exist
            mkdir -p /var/www/sshappy
            cd /var/www/sshappy
            
            # Pull latest code
            if [ -d ".git" ]; then
              git pull origin main
            else
              git clone https://github.com/dutchiono/sshappy.git .
            fi
            
            # Create builds directory for APK storage
            mkdir -p builds
            
            # Set proper permissions
            chown -R www-data:www-data /var/www/sshappy
            chmod -R 755 /var/www/sshappy
            
            # Reload nginx if config changed
            nginx -t && systemctl reload nginx || true
            
            echo "✅ Deployment complete! Website live at your configured domain"

      - name: Notify deployment status
        if: always()
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            echo "🚀 Deployment successful!"
          else
            echo "❌ Deployment failed"
            exit 1
          fi
